#!/bin/bash

# #
#   @project        TVApp2
#   @usage          Automatic m3u and xml guide updater for TheTvApp, TVPass, and MoveOnJoy utilized within your IPTV client.
#   @file           plugins
#   @repo.1         https://github.com/BinaryNinja/tvapp2
#   @repo.2         https://git.binaryninja.net/BinaryNinja/tvapp2
#   @repo.3         https://github.com/aetherinox/docker-base-alpine
# #

PLUGINS_PATH="/config/www/plugins"

# #
#   Plugins > Start
# #

echo -e " Loader       : Checking tvapp2-plugins"
