name: "🐛 Bug Report"
description: Found something you weren't expecting? Report it here!
title: "🐛 Bug: <title>"
labels: [
  "Type ◦ Bug"
]
body:
  - type: markdown
    attributes:
      value: |
        1. Please speak `English`.
        2. Make sure you are using the latest version and take a moment to check that your issue hasn't been reported before.
        3. It's really important to provide pertinent details and logs, incomplete details will be handled as an invalid report.
        4. Before creating this bug report, ensure you updated your applications to the latest versions.
           Check your configurations to ensure there are no typos or errors.
           Docker users should attempt to re-pull the TVApp2 image to ensure caching is not the cause of an issue.

        <br />

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please provide a description of your issue here.
    validations:
      required: true

  - type: textarea
    id: steps-reproduce
    attributes:
      label: Steps To Reproduce
      description: |
        Describe the steps that need taken by the developer to get the error / issue you're experiencing.
      value: |
        -
        -
        -
        -
    validations:
      required: true

  - type: input
    id: version-tvapp2
    attributes:
      label: "Version - Tag"
      description: |
        Version / tag you are pulling for `TVApp2`.
        You can view your build version in terminal by typing `docker inspect tvapp2 | grep BUILDVERSION`
      placeholder: "Ex: 1.0.0"
    validations:
      required: true

  - type: input
    id: version-docker
    attributes:
      label: "Version - Docker"
      description: "Version of docker you are running. Use command `docker --version`."
      placeholder: "Ex: 27.2.0, build 3ab4256"
    validations:
      required: true

  - type: dropdown
    id: image-registry
    attributes:
      label: Docker Image Registry
      description: |
        Select which docker image you are pulling from.
        If you custom built your image, ensure it's not a problem with your code before submitting this bug report.
      options:
        - "Dockerhub"
        - "Gitea"
        - "Github"
        - "Manual Build"
    validations:
      required: true

  - type: dropdown
    id: app-parent
    attributes:
      label: Parent App
      description: |
        Select the application you are using TVApp2 with. Jellyfin, Plex, Emby, etc.
      options:
        - "Dim"
        - "Emby"
        - "Jellyfin"
        - "KODI"
        - "Plex"
        - "Other (specify in description)"
    validations:
      required: true

  - type: dropdown
    id: app-proxy
    attributes:
      label: Proxy App
      description: |
        Select the plugin / app (if any) you are using as a m3u "Proxy" between your parent streaming app and TVApp2.
      options:
        - "❌ No Proxy"
        - "Cabernet"
        - "IPTVBoss"
        - "IPTV-Solution"
        - "Threadfin"
        - "xTeVe"
        - "Other (specify in description)"
    validations:
      required: true

  - type: dropdown
    id: priority-type
    attributes:
      label: Priority
      description: |
        How critical is the issue?
        Do not abuse this. Issues that completely break the utility would be classified as critical
      options:
        - "Low"
        - "Normal"
        - "High"
        - "Urgent"
    validations:
      required: true

  - type: textarea
    id: docker-compose
    attributes:
      label: docker-compose.yml
      description: |
        Copy / paste your `docker-compose.yml` file here

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Paste your docker logs here.
        You can get your docker logs by opening terminal and running `docker logs tvapp2`

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        Please provide screenshots of any errors or the issue you're having.
        Gifs are even better.
