#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# #
#   @project        TVApp2
#   @usage          Automatic m3u and xml guide updater for TheTvApp, TVPass, and MoveOnJoy utilized within your IPTV client.
#   @file           run
#   @repo.1         https://github.com/BinaryNinja/tvapp2
#   @repo.2         https://git.binaryninja.net/BinaryNinja/tvapp2
#   @repo.3         https://github.com/aetherinox/docker-base-alpine
# #
