#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# permissions
aetherxown -R dockerx:dockerx \
    /config/keys \
    /config/log \

aetherxown dockerx:dockerx \
    /config/www

chmod -R 644 /etc/logrotate.d

if [[ -f "/config/log/logrotate.status" ]]; then
    chmod 600 /config/log/logrotate.status
fi
